package tui

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/aymenhmaidiwastaken/devboot/internal/deps"
	"github.com/aymenhmaidiwastaken/devboot/internal/profile"
	"github.com/aymenhmaidiwastaken/devboot/internal/shell"
	"github.com/charmbracelet/huh"
	"gopkg.in/yaml.v3"
)

// RunInitWizard runs an interactive init wizard using huh forms.
func RunInitWizard() error {
	var (
		name      string
		email     string
		shellType string
		useProfile  bool
		selectedProfile string
		selectedTools []string
		selectedPlugins []string
	)

	// Step 1: User info
	err := huh.NewForm(
		huh.NewGroup(
			huh.NewNote().
				Title("  devboot init").
				Description("Let's set up your dev environment config.\n"),

			huh.NewInput().
				Title("Your name (for git)").
				Value(&name).
				Placeholder("Jane Doe"),

			huh.NewInput().
				Title("Your email (for git)").
				Value(&email).
				Placeholder("jane@example.com"),

			huh.NewSelect[string]().
				Title("Shell").
				Options(
					huh.NewOption("zsh", "zsh"),
					huh.NewOption("bash", "bash"),
					huh.NewOption("fish", "fish"),
				).
				Value(&shellType),
		),
	).Run()
	if err != nil {
		return err
	}

	if shellType == "" {
		shellType = string(shell.Detect())
	}

	// Step 2: Profile or custom
	err = huh.NewForm(
		huh.NewGroup(
			huh.NewConfirm().
				Title("Start from a profile?").
				Description("Profiles are curated tool sets (frontend, backend, devops, etc.)").
				Value(&useProfile),
		),
	).Run()
	if err != nil {
		return err
	}

	if useProfile {
		profileNames := profile.List()
		var options []huh.Option[string]
		for _, name := range profileNames {
			p, _ := profile.Get(name)
			options = append(options, huh.NewOption(
				fmt.Sprintf("%s — %s", p.Name, p.Description),
				name,
			))
		}

		err = huh.NewForm(
			huh.NewGroup(
				huh.NewSelect[string]().
					Title("Choose a profile").
					Options(options...).
					Value(&selectedProfile),
			),
		).Run()
		if err != nil {
			return err
		}
	}

	// Step 3: Tool selection
	categories := deps.Categories()
	var catNames []string
	for cat := range categories {
		catNames = append(catNames, cat)
	}
	sort.Strings(catNames)

	var toolOptions []huh.Option[string]
	for _, cat := range catNames {
		tools := categories[cat]
		sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })
		for _, t := range tools {
			label := fmt.Sprintf("[%s] %s — %s", cat, t.Name, t.Description)
			toolOptions = append(toolOptions, huh.NewOption(label, t.Name))
		}
	}

	// Pre-select tools from profile
	if selectedProfile != "" {
		p, _ := profile.Get(selectedProfile)
		selectedTools = append(selectedTools, p.Tools...)
	}

	err = huh.NewForm(
		huh.NewGroup(
			huh.NewMultiSelect[string]().
				Title("Select tools to install").
				Options(toolOptions...).
				Value(&selectedTools).
				Height(15),
		),
	).Run()
	if err != nil {
		return err
	}

	// Step 4: Shell plugins
	if shellType == "zsh" {
		pluginOptions := []huh.Option[string]{
			huh.NewOption("zsh-autosuggestions — Fish-like suggestions", "zsh-autosuggestions"),
			huh.NewOption("zsh-syntax-highlighting — Command highlighting", "zsh-syntax-highlighting"),
			huh.NewOption("fzf-tab — Fuzzy completion", "fzf-tab"),
			huh.NewOption("zsh-completions — Extra completions", "zsh-completions"),
		}

		err = huh.NewForm(
			huh.NewGroup(
				huh.NewMultiSelect[string]().
					Title("Select zsh plugins").
					Options(pluginOptions...).
					Value(&selectedPlugins).
					Height(8),
			),
		).Run()
		if err != nil {
			return err
		}
	}

	// Build config
	cfg := buildConfig(name, email, shellType, selectedProfile, selectedTools, selectedPlugins)

	// Write file
	path := "devboot.yaml"
	if _, err := os.Stat(path); err == nil {
		var overwrite bool
		huh.NewForm(
			huh.NewGroup(
				huh.NewConfirm().
					Title("devboot.yaml already exists. Overwrite?").
					Value(&overwrite),
			),
		).Run()
		if !overwrite {
			fmt.Println("  Aborted.")
			return nil
		}
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}

	header := "# devboot.yaml — generated by devboot init\n# Run: devboot apply\n\n"
	os.WriteFile(path, []byte(header+string(data)), 0644)

	fmt.Println()
	fmt.Println(successStyle.Render("  ✓ Created devboot.yaml"))
	fmt.Println(dimStyle.Render("    Run: devboot apply"))
	fmt.Println()

	return nil
}

func buildConfig(name, email, shellType, profileName string, tools, plugins []string) map[string]interface{} {
	cfg := map[string]interface{}{}

	// Tools
	if len(tools) > 0 {
		cfg["tools"] = tools
	}

	// Shell
	shellCfg := map[string]interface{}{
		"type": shellType,
	}

	aliases := map[string]string{
		"g":  "git",
		"ll": "ls -la",
	}

	// Merge profile aliases
	if profileName != "" {
		p, ok := profile.Get(profileName)
		if ok {
			for k, v := range p.Shell.Aliases {
				aliases[k] = v
			}
		}
	}

	shellCfg["aliases"] = aliases
	shellCfg["env"] = map[string]string{"EDITOR": "vim"}

	if len(plugins) > 0 {
		shellCfg["plugins"] = plugins
	}
	cfg["shell"] = shellCfg

	// Git
	gitCfg := map[string]interface{}{
		"user.name":          name,
		"user.email":         email,
		"init.defaultBranch": "main",
		"pull.rebase":        true,
		"aliases": map[string]string{
			"co": "checkout",
			"br": "branch",
			"st": "status",
			"lg": "log --oneline --graph --decorate",
		},
	}
	cfg["git"] = gitCfg

	// VSCode from profile
	if profileName != "" {
		p, ok := profile.Get(profileName)
		if ok && len(p.VSCode.Extensions) > 0 {
			cfg["vscode"] = map[string]interface{}{
				"extensions": p.VSCode.Extensions,
			}
		}
	}

	return cfg
}

// RunAddTool runs an interactive tool picker for `devboot add`.
func RunAddTool() ([]string, error) {
	categories := deps.Categories()
	var catNames []string
	for cat := range categories {
		catNames = append(catNames, cat)
	}
	sort.Strings(catNames)

	var toolOptions []huh.Option[string]
	for _, cat := range catNames {
		tools := categories[cat]
		sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })
		for _, t := range tools {
			installed := ""
			if deps.GetBinName(t.Name) != "" {
				// Show if already installed
				if _, err := os.Stat(""); err == nil {
					// Just show the tool
				}
			}
			label := fmt.Sprintf("[%s] %s — %s%s", cat, t.Name, t.Description, installed)
			toolOptions = append(toolOptions, huh.NewOption(label, t.Name))
		}
	}

	var selected []string
	err := huh.NewForm(
		huh.NewGroup(
			huh.NewMultiSelect[string]().
				Title("Select tools to add").
				Options(toolOptions...).
				Value(&selected).
				Height(15),
		),
	).Run()

	return selected, err
}

// RunStatusDashboard renders a dashboard view of the current status.
func RenderStatusDashboard(sections []StatusSection) string {
	var sb strings.Builder

	sb.WriteString(titleStyle.Render("  devboot status"))
	sb.WriteString("\n\n")

	for _, section := range sections {
		sb.WriteString(sectionStyle.Render(fmt.Sprintf("  ▸ %s", section.Name)))
		sb.WriteString("\n")

		for _, item := range section.Items {
			var icon, line string
			switch item.Status {
			case "ok":
				icon = successStyle.Render("✓")
				line = successStyle.Render(item.Label)
			case "missing":
				icon = failStyle.Render("✗")
				line = failStyle.Render(item.Label)
			case "info":
				icon = dimStyle.Render("●")
				line = dimStyle.Render(item.Label)
			case "warn":
				icon = progressStyle.Render("⚠")
				line = progressStyle.Render(item.Label)
			}
			sb.WriteString(fmt.Sprintf("    %s %s\n", icon, line))
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

type StatusSection struct {
	Name  string
	Items []StatusItem
}

type StatusItem struct {
	Label  string
	Status string // "ok", "missing", "info", "warn"
}
