package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"

	"github.com/aymenhmaidiwastaken/devboot/internal/deps"
	"github.com/aymenhmaidiwastaken/devboot/internal/shell"
	"github.com/aymenhmaidiwastaken/devboot/internal/ui"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var exportCmd = &cobra.Command{
	Use:   "export",
	Short: "Export current environment as a devboot.yaml (smart detection)",
	RunE:  runExport,
}

func init() {
	rootCmd.AddCommand(exportCmd)
}

type exportConfig struct {
	Tools  []string          `yaml:"tools,omitempty"`
	Shell  exportShell       `yaml:"shell,omitempty"`
	Git    exportGit         `yaml:"git,omitempty"`
	VSCode exportVSCode      `yaml:"vscode,omitempty"`
}

type exportShell struct {
	Type    string            `yaml:"type,omitempty"`
	Aliases map[string]string `yaml:"aliases,omitempty"`
	Env     map[string]string `yaml:"env,omitempty"`
	Plugins []string          `yaml:"plugins,omitempty"`
}

type exportGit struct {
	UserName          string            `yaml:"user.name,omitempty"`
	UserEmail         string            `yaml:"user.email,omitempty"`
	InitDefaultBranch string            `yaml:"init.defaultBranch,omitempty"`
	PullRebase        string            `yaml:"pull.rebase,omitempty"`
	Aliases           map[string]string `yaml:"aliases,omitempty"`
}

type exportVSCode struct {
	Extensions []string `yaml:"extensions,omitempty"`
}

func runExport(cmd *cobra.Command, args []string) error {
	ui.Section("Scanning environment...")

	cfg := exportConfig{}

	// 1. Detect installed tools from the registry
	for name, info := range deps.Registry {
		binName := info.BinName
		if binName == "" {
			binName = name
		}
		if _, err := exec.LookPath(binName); err == nil {
			cfg.Tools = append(cfg.Tools, name)
		}
	}

	// 2. Also check brew list / apt list for additional packages
	if extraTools := detectBrewPackages(); len(extraTools) > 0 {
		ui.Info(fmt.Sprintf("detected %d additional brew packages", len(extraTools)))
	}

	// 3. Shell detection
	cfg.Shell.Type = string(shell.Detect())

	// 4. Parse existing shell config for aliases and env vars
	shellType := shell.Detect()
	configFile := shell.ConfigFile(shellType)
	aliases, envVars, plugins := parseShellConfig(configFile)
	if len(aliases) > 0 {
		cfg.Shell.Aliases = aliases
		ui.Info(fmt.Sprintf("found %d aliases in %s", len(aliases), filepath.Base(configFile)))
	}
	if len(envVars) > 0 {
		cfg.Shell.Env = envVars
		ui.Info(fmt.Sprintf("found %d env vars", len(envVars)))
	}
	if len(plugins) > 0 {
		cfg.Shell.Plugins = plugins
		ui.Info(fmt.Sprintf("found %d shell plugins", len(plugins)))
	}

	// 5. Git config — read all relevant settings
	cfg.Git.UserName = gitConfigGet("user.name")
	cfg.Git.UserEmail = gitConfigGet("user.email")
	cfg.Git.InitDefaultBranch = gitConfigGet("init.defaultBranch")
	cfg.Git.PullRebase = gitConfigGet("pull.rebase")

	// Git aliases
	gitAliases := detectGitAliases()
	if len(gitAliases) > 0 {
		cfg.Git.Aliases = gitAliases
		ui.Info(fmt.Sprintf("found %d git aliases", len(gitAliases)))
	}

	// 6. VS Code extensions
	if extensions := detectVSCodeExtensions(); len(extensions) > 0 {
		cfg.VSCode.Extensions = extensions
		ui.Info(fmt.Sprintf("found %d VS Code extensions", len(extensions)))
	}

	// 7. Detect prompt
	if _, err := exec.LookPath("starship"); err == nil {
		found := false
		for _, t := range cfg.Tools {
			if t == "starship" {
				found = true
				break
			}
		}
		if !found {
			cfg.Tools = append(cfg.Tools, "starship")
		}
		ui.Info("detected Starship prompt")
	}

	out, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}

	fmt.Printf("\n# devboot.yaml — exported from current environment\n# Generated by: devboot export\n# Platform: %s/%s\n\n%s",
		runtime.GOOS, runtime.GOARCH, string(out))
	return nil
}

func parseShellConfig(path string) (aliases map[string]string, envVars map[string]string, plugins []string) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, nil
	}
	content := string(data)
	lines := strings.Split(content, "\n")

	aliases = make(map[string]string)
	envVars = make(map[string]string)

	aliasRegex := regexp.MustCompile(`^alias\s+(\w+)=['"](.*?)['"]`)
	exportRegex := regexp.MustCompile(`^export\s+(\w+)=(.*)`)
	fishAliasRegex := regexp.MustCompile(`^alias\s+(\w+)\s+'(.*?)'`)
	fishEnvRegex := regexp.MustCompile(`^set\s+-gx\s+(\w+)\s+(.*)`)

	// Plugin detection patterns
	pluginPatterns := map[string]*regexp.Regexp{
		"zsh-autosuggestions":     regexp.MustCompile(`zsh-autosuggestions`),
		"zsh-syntax-highlighting": regexp.MustCompile(`zsh-syntax-highlighting`),
		"fzf-tab":                 regexp.MustCompile(`fzf-tab`),
		"zsh-completions":         regexp.MustCompile(`zsh-completions`),
	}

	seenPlugins := make(map[string]bool)

	for _, line := range lines {
		line = strings.TrimSpace(line)

		// Skip comments
		if strings.HasPrefix(line, "#") {
			continue
		}

		// Aliases
		if m := aliasRegex.FindStringSubmatch(line); len(m) == 3 {
			aliases[m[1]] = m[2]
		} else if m := fishAliasRegex.FindStringSubmatch(line); len(m) == 3 {
			aliases[m[1]] = m[2]
		}

		// Env vars
		if m := exportRegex.FindStringSubmatch(line); len(m) == 3 {
			val := strings.Trim(m[2], `"'`)
			// Skip PATH modifications and other noisy vars
			if m[1] != "PATH" && m[1] != "MANPATH" && !strings.Contains(val, "$") {
				envVars[m[1]] = val
			}
		} else if m := fishEnvRegex.FindStringSubmatch(line); len(m) == 3 {
			envVars[m[1]] = m[2]
		}

		// Plugins
		for name, pattern := range pluginPatterns {
			if pattern.MatchString(line) && !seenPlugins[name] {
				plugins = append(plugins, name)
				seenPlugins[name] = true
			}
		}
	}

	// Clean up empty maps
	if len(aliases) == 0 {
		aliases = nil
	}
	if len(envVars) == 0 {
		envVars = nil
	}

	return
}

func detectGitAliases() map[string]string {
	cmd := exec.Command("git", "config", "--global", "--get-regexp", "^alias\\.")
	out, err := cmd.Output()
	if err != nil {
		return nil
	}

	aliases := make(map[string]string)
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, " ", 2)
		if len(parts) == 2 {
			name := strings.TrimPrefix(parts[0], "alias.")
			aliases[name] = parts[1]
		}
	}
	return aliases
}

func detectVSCodeExtensions() []string {
	for _, bin := range []string{"code", "code-insiders", "codium"} {
		if _, err := exec.LookPath(bin); err == nil {
			cmd := exec.Command(bin, "--list-extensions")
			out, err := cmd.Output()
			if err == nil {
				var extensions []string
				for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
					line = strings.TrimSpace(line)
					if line != "" {
						extensions = append(extensions, line)
					}
				}
				return extensions
			}
		}
	}
	return nil
}

func detectBrewPackages() []string {
	if _, err := exec.LookPath("brew"); err != nil {
		return nil
	}
	cmd := exec.Command("brew", "list", "--formula", "-1")
	out, err := cmd.Output()
	if err != nil {
		return nil
	}
	var packages []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			packages = append(packages, line)
		}
	}
	return packages
}

func gitConfigGet(key string) string {
	cmd := exec.Command("git", "config", "--global", "--get", key)
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}
